services:
  nuxt-app:
    platform: linux/arm64/v8
    image: captainigl00/brasseriechezju:latest
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    platform: linux/arm64/v8
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/letsencrypt:ro
      - ./public:/usr/share/nginx/html/public:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxt-app
    restart: unless-stopped

  certbot:
    platform: linux/arm64/v8
    image: certbot/certbot:arm64v8-latest
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"

